# Generated by Django 5.1.13 on 2025-10-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ggg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_nigga', models.IntegerField(default=0)),
                ('nigga_text', models.CharField(max_length=300)),
            ],
        ),
    ]
