# Generated by Django 5.1.13 on 2025-10-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('Pass', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ggg',
        ),
    ]
